### ISSUE TITLE
TLS/SSL対応

### ISSUE THREAD

**Issue by nanasess** [ec-cube2/docker#1]
4系で進めている OWASP ZAP の対応を2系にも移植したいと考えています。
https://github.com/EC-CUBE/ec-cube/pull/4694
https://github.com/EC-CUBE/ec-cube2/issues/424

OWASP ZAP の local proxies を活用するために、 TLS/SSL自己証明書を利用したいと思っています。
以下のようなパッチで動作確認済みですが、方針としていかがでしょうか？
(本イメージには取り込まず、 EC-CUBE側の Dockerfile で独自に対応した方が望ましければ、そうしたいと思います)

```diff
diff --git a/php/7.4/apache/Dockerfile b/php/7.4/apache/Dockerfile
index 89b5244..7cb69f9 100644
--- a/php/7.4/apache/Dockerfile
+++ b/php/7.4/apache/Dockerfile
@@ -11,6 +11,7 @@ RUN apt-get update \
         libpq-dev \
         libzip-dev zlib1g-dev \
         libpcre3-dev \
+        ssl-cert \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*
 RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
@@ -27,3 +28,8 @@ COPY docker-php-entrypoint /usr/local/bin/

 # workdir
 WORKDIR /var/www/app
+
+# Enable SSL
+RUN a2enmod ssl
+RUN a2ensite default-ssl
+EXPOSE 443
```

**Comment by ttsuru** [comment]
@nanasess 
ありがとうございます。こちら問題はないかと思います。
Nginx含め対応できるとよさそうですね。

**Comment by ttsuru** [comment]
DockerのBuildはDockerhubからGitHub Actionsに移行を検討しています。
また、古いPHPバージョンのDockerベースイメージのメンテについても別途検討したいと思っています。

**Comment by ttsuru** [comment]
Nginx は以下を使えば自動で行けますね。
https://github.com/nginx-proxy/nginx-proxy
https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion

**Comment by nanasess** [comment]
> Nginx は以下を使えば自動で行けますね。

自己証明書のものもありました。
https://github.com/sebastienheyd/docker-self-signed-proxy-companion

Nginx は、こちらを使うことにして、 apache の方だけ PR しますね
